all: setup-configs enable-1password-ssh setup-vscode

setup-configs:
    rsync -a /opt/post-install/.config/ ~/.config/
    ln -sfn $DISTROBOX_HOST_HOME/.gitconfig ~/.gitconfig

enable-1password-ssh:
    ln -sfn $DISTROBOX_HOST_HOME/.1password ~/.1password
    mkdir -p ~/.ssh
    cp $DISTROBOX_HOST_HOME/.ssh/config ~/.ssh/config
    sudo ln -sfn /run/host/opt/1Password /opt/1Password

setup-vscode:
    mkdir -p ~/.vscode-extensions
    grep -v '^#' vscode-extensions.list | sed 's/\(.*\)/--install-extension \1/' | xargs code --extensions-dir $HOME/.vscode-extensions
