all: setup-configs enable-1password-ssh setup-vscode

setup-configs:
    rsync -a /opt/post-install/.config/ ~/.config/
    ln -s $DISTROBOX_HOST_HOME/.gitconfig ~/.gitconfig

enable-1password-ssh:
    ln -s $DISTROBOX_HOST_HOME/.1password ~/.1password
    mkdir -p ~/.ssh
    cp $DISTROBOX_HOST_HOME/.ssh/config ~/.ssh/config

setup-vscode:
    mkdir -p ~/.vscode-extensions
    grep -v '^#' /opt/post-install/vscode-extensions.list | xargs -I {} code --extensions-dir ~/.vscode-extensions --install-extension {}

install-additional-go-versions:
    grep -v '^#' /opt/post-install/goversions.list | sed 's/\(.*\)/golang.org\/dl\/\1@latest/' | xargs go install
    grep -v '^#' /opt/post-install/goversions.list | xargs -I {} sh -c '{} download'
